// Code generated by hertz generator.

package main

import (
	"douyin-demo/biz/dal"

	"github.com/cloudwego/hertz/pkg/app/server"
)

func main() {
	dal.Init()
	// h := server.Default()
	h := server.New(server.WithMaxRequestBodySize(4 * 1024 * 1024 * 1024))

	register(h)
	h.Spin()
}
